### ISSUE TITLE
Version 1.1 roadmap

### ISSUE THREAD

**Issue by franciscop** [franciscop/server#78]
A list of things still needed to release the much-awaited version `1.1` with plugins:

- [x] test option parser more in-depth. Specially for plugins and things like `parent`.
- [ ] make some magic for `router` and `reply` to be extensible from the plugins.
- [x] try more the testing framework. Few alpha releases needed as I find the sweet spot.
- [x] test the testing framework (lol), specially around plugins.
- [x] clean up the code a bit: move `src/config` to `utils/options`
- [ ] document few things:
  - [ ] smaller and well-tested features like the better `engine`.
  - [ ] plugins! have to write the whole documentation and haven't started yet. Some info is scattered through the issues in this repo.
  - [ ] testing for devs. some work is underway, but depends on finding a better API first.
  - [ ] websockets. They are working pretty well, but now we have to make the documentation. It is halfway through though.

It is actually a lot more than I thought, but it's good to have a list where I can cross things as I fix them. Some items are 30-60 mins and some are 1-10 hours.

**Comment by franciscop** [comment]
I think the testing one can be ticked as well, got 100% coverage on everything :muscle: :

![100](https://user-images.githubusercontent.com/2801252/37149436-4ae22c56-2311-11e8-9ebf-ef8c07f5ecec.png)

**Comment by franciscop** [comment]
So... version 1.1 never happened, and my life priorities changed along the way. I will try my best to keep supporting `1.0.x`, and I use that version continuously, but right now I don't have the time/energy to move a project of this size into 1.1 or 2.0.

**Comment by SidneyNemzer** [comment]
Totally understandable, I really appreciate the time you've dedicated so far!
